{
 "title": "CNPG PgBouncer Pooler",
 "description": "A visual representation of Prometheus metrics collected from CNPG PgBouncer Pooler",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cnpg_pgbouncer_pools_cl_active,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cnpg_pgbouncer_pools_cl_active{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "cnpg_cluster",
    "label": "CNPG Cluster",
    "query": {
     "query": "label_values(cnpg_pgbouncer_pools_cl_active{cluster=\"$cluster\", namespace=\"$namespace\"},cnpg_cluster)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(cnpg_pgbouncer_pools_cl_active{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\"},database)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(cnpg_pgbouncer_pools_cl_active{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=\"$database\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_pools_pool_mode{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Pooling mode"
    }
   ]
  },
  { "title": "Queries & Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cnpg_pgbouncer_stats_total_query_count{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}[5m])",
     "legendFormat": "Queries per Second -"
    }
   ]
  },
  {
   "title": "Queries & Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_stats_avg_query_count{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Queries/sec -"
    },
    {
     "expr": "cnpg_pgbouncer_stats_avg_xact_count{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Transactions/sec -"
    }
   ]
  },
  {
   "title": "Average Query Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_stats_avg_query_time{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Avg query time -"
    }
   ]
  },
  {
   "title": "Idle in Transaction percent of time",
   "type": "timeseries",
   "description": "Helps to estimate percentage of the time connections from PgBouncer are in the \"idle\" state in PostgreSQL",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "1 - cnpg_pgbouncer_stats_avg_query_time{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"} / cnpg_pgbouncer_stats_avg_xact_time{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Idle in Transaction -"
    }
   ]
  },
  {
   "title": "Average Client Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_stats_avg_wait_time{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Avg Wait Time -"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_stats_avg_recv{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Received -"
    },
    {
     "expr": "cnpg_pgbouncer_stats_avg_sent{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
     "legendFormat": "Sent -"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cnpg_pgbouncer_pools_sv_active{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Active conn (sv_active)"
      },
      {
       "expr": "cnpg_pgbouncer_pools_sv_idle{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Idle conn (sv_idle)"
      },
      {
       "expr": "cnpg_pgbouncer_pools_sv_login{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Login conn (sv_login)"
      },
      {
       "expr": "cnpg_pgbouncer_pools_sv_tested{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Tested conn (sv_tested)"
      },
      {
       "expr": "cnpg_pgbouncer_pools_sv_used{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Used conn (sv_used)"
      }
     ]
    },
    {
     "title": "Count of Servers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cnpg_pgbouncer_lists_used_servers{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", pod=\"$pod\"}",
       "legendFormat": "Used Servers -"
      },
      {
       "expr": "cnpg_pgbouncer_lists_free_servers{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", pod=\"$pod\"}",
       "legendFormat": "Free Servers -"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cnpg_pgbouncer_pools_cl_active{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Active conn (cl_active)"
      },
      {
       "expr": "cnpg_pgbouncer_pools_cl_waiting{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Waiting conn (cl_waiting)"
      }
     ]
    },
    {
     "title": "Maximum Client Wait Time",
     "type": "timeseries",
     "description": "How long the first (oldest) client in the queue has waited, in seconds. If this starts increasing, then the current pool of servers does not handle requests quickly enough. The reason may be either an overloaded server or just too small of a pool_size setting.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "cnpg_pgbouncer_pools_maxwait_us{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", database=~\"$database\", pod=\"$pod\"}",
       "legendFormat": "Max Wait Time -"
      }
     ]
    },
    {
     "title": "Client Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cnpg_pgbouncer_lists_used_clients{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", pod=\"$pod\"}",
       "legendFormat": "Used Clients -"
      },
      {
       "expr": "cnpg_pgbouncer_lists_free_clients{cluster=\"$cluster\", namespace=\"$namespace\", cnpg_cluster=\"$cnpg_cluster\", pod=\"$pod\"}",
       "legendFormat": "Free Clients -"
      }
     ]
    }
   ]
  }
 ]
}